version: '3'
services:
  my_db:
    image: 'mysql:5.7'
    restart: on-failure
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - /Users/polishchuk/Downloads/hworknet_test2.sql:/usr/dump.sql
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      spring.datasource.url: 'jdbc:mysql://my_db:3306/db?characterEncoding=UTF-8'
      spring.datasource.username: 'root'
      spring.datasource.password: 'root'
      PORT: '8081'
    ports:
      - '8080:8080'
    expose:
      - '8080'
    depends_on:
      - my_db


