services:
  my_db:
    image: 'mysql:8'
    restart: on-failure
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my_db_data:/var/lib/mysql
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      spring.datasource.url: 'jdbc:mysql://my_db:3306/db?characterEncoding=UTF-8'
      spring.datasource.username: 'root'
      spring.datasource.password: 'root'
      PORT: '8081'
    ports:
      - '8080:8080'
    expose:
      - '8080'
    depends_on:
      - my_db

volumes:
  my_db_data:
    driver: local