spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db?characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect
  devtools:
    restart:
      additional-paths: src/main/java/com/volodymyrpo/eit
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  flyway:
    baseline-on-migrate: true

server:
  port: 8080
  connection-timeout:

jwt:
  secret: 'Q7YqENaErYejz37UYTDA2E7czKNJQ7YqENaErYejz37UYTDA2E7czKNJQ7YqENaErYejz37UYTDA2E7czKNJ'
  expiration: 604000
  header: 'Authorization'
  route:
    authentication:
      path: '/auth'
      refresh: '/refresh'

cross.origin: '*'
