spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  devtools:
    restart:
      additional-paths: src/main/java/com/volodymyrpo/eit
      enabled: true

  flyway:
    baseline-on-migrate: true
server:
  port: 8080
  connection-timeout:

jwt:
  secret: 'Q7YqENaErYejz37UYTDA2E7czKNJ'
  expiration: 604000
  header: 'Authorization'
  route:
    authentication:
      path: '/auth'
      refresh: '/refresh'

cross.origin: '*'
